task: regression

profiler:
    type: TransformerRegressor
    params:
      trainer:
        gpus: 1
        max_epochs: 5
        accumulate_grad_batches: 2
      network:
        output_normalized: true
        pretrained_model_name_or_path: gpt2
        lr: 4e-5
      data_loader:
        batch_size: 1
      val_ratio: 0.2
      max_length: null

dataset:
    type: asap-aes
    params:
        path: /workspace/data/prompt_1.tsv