task: regression
profiler:
  type: TransformerRegressor
  params:
    trainer:
      gpus: 1
      max_epochs: 10
      accumulate_grad_batches: 2
    network:
      output_normalized: true
      pretrained_model_name_or_path: distilbert-base-uncased
      lr: 4.0e-05
    data_loader:
      batch_size: 16
    val_ratio: 0.2
    max_length: null
dataset:
  type: asap-aes
  params:
    path: /workspace/data/prompt_1.tsv
    prompt_id: 1
