
task: classification

profiler:
    type: DocFeatureMLClassifier
    params:
        features:
            - type: NumberOfTokenFeature
              params:
            - type: AverageTokenLengthFeature
              params:
            - type: UnigramLikelihoodFeature
              params:
                path: data/example/dummy_unigram.tsv
        classifier:
            type: rf
            params:
                n_estimators: 50
                max_depth: 5
                random_state: 46

dataset:
    type: asap-aes
    params:
        path: /workspace/data/training_set_rel3.tsv